---
title: "cfDNA dynamics"
subtitle: "MSK SPECTRUM"
author:
  - "Marc Williams"
  - "Ignacio Vazquez-Garcia"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output: 
  html_document:
    highlight: tango
    df_print: paged
    code_folding: hide
    fig_align: center
    toc: true
    toc_float: true
    toc_depth: 3
    number_sections: yes
params:
   rmd: "220_cfdna_dynamics.Rmd"
---

```{r setup, include=FALSE}
# Global knit options
knitr::opts_knit$set(root.dir = rprojroot::find_rstudio_root_file())

# Global chunk options
knitr::opts_chunk$set(echo=FALSE, tidy=TRUE, warning=FALSE, message=FALSE)
```

```{r, include=FALSE}
library(tidyverse)
library(ggplot2)
library(ggpubr)
library(ggrepel)
library(cowplot)
library(scales)
library(lubridate)

source("src/global_vars.R")

db <- db %>%
  map(~mutate(.x, patient_id_short = str_remove_all(patient_id, "SPECTRUM-OV-")))
```

## cfDNA time series

### All patients

```{r, fig.width=9, fig.height=17}

p <- db$specimens_lab_medicine %>%
  filter(patient_id %in% included_patients) %>%
  group_by(patient_id, specimen_lab_medicine_sample_status) %>%
  arrange(specimen_lab_medicine_drawn_date) %>%
  dplyr::mutate(specimen_lab_medicine_drawn_date_diff = specimen_lab_medicine_drawn_date - first(specimen_lab_medicine_drawn_date)) %>%
  ggplot() +
  aes(x=specimen_lab_medicine_drawn_date_diff, y=reorder(patient_id_short, desc(patient_id)), 
      col=specimen_lab_medicine_sample_status, label=specimen_lab_medicine_sample_status, size=specimen_lab_medicine_cfdna_total_yield) +
  geom_point(alpha = 0.5) +
  scale_x_continuous(breaks = scales::breaks_width(365)) +
  labs(title = "Plasma/buffy coat samples", x = "Time from baseline (days)", y = "Patients",
       color = "Sample type", size = "cfDNA total yield") +
  theme(
    legend.position="right",
    panel.grid.major.x = element_line(size=.1, color="grey50", linetype = "dashed")
  )

p

```


### Patients with scDNA

```{r, fig.width=9, fig.height=6}

p <- db$specimens_lab_medicine %>%
  filter(patient_id %in% scdna_patients) %>%
  group_by(patient_id, specimen_lab_medicine_sample_status) %>%
  arrange(specimen_lab_medicine_drawn_date) %>%
  dplyr::mutate(specimen_lab_medicine_drawn_date_diff = specimen_lab_medicine_drawn_date - first(specimen_lab_medicine_drawn_date)) %>%
  ggplot() +
  aes(x=specimen_lab_medicine_drawn_date_diff, y=reorder(patient_id_short, desc(patient_id)), 
      col=specimen_lab_medicine_sample_status, label=specimen_lab_medicine_sample_status, size=specimen_lab_medicine_cfdna_total_yield) +
  geom_point(alpha = 0.5) +
  scale_x_continuous(breaks = scales::breaks_width(365)) +
  labs(title = "Plasma/buffy coat samples", x = "Time from baseline (days)", y = "Patients",
       color = "Sample type", size = "cfDNA total yield") +
  theme(
    legend.position="right",
    panel.grid.major.x = element_line(size=.1, color="grey50", linetype = "dashed")
  )

p

```

### CA125 + survival + recurrence + surgery + cfDNA 

```{r}

biomarkers_tbl <- db$laboratory_tests %>% 
  dplyr::filter(patient_id %in% included_patients,
                laboratory_test_name %in% c("Cancer Antigen 125 (CA 125)"))

recur <- db$response

cfdna <- db$specimens_lab_medicine

first_date <- bind_rows(select(biomarkers_tbl, patient_id, laboratory_test_date), 
                        select(recur, patient_id, response_first_recurrence_ct_scan_date),
                        select(cfdna, patient_id, specimen_lab_medicine_drawn_date)) %>% 
  mutate(laboratory_test_date = as.difftime(laboratory_test_date)) %>%
  group_by(patient_id) %>% 
  summarize(laboratory_test_date_first = as.difftime(first(na.omit(laboratory_test_date)), units = "days"),
            response_first_recurrence_ct_scan_date_first = as.difftime(first(na.omit(response_first_recurrence_ct_scan_date)), units = "days"),
            specimen_lab_medicine_drawn_date_first = as.difftime(first(na.omit(specimen_lab_medicine_drawn_date)), units = "days"),
            first_date = as.difftime(first(laboratory_test_date_first, specimen_lab_medicine_drawn_date_first), units = "days")) %>%
  ungroup

# CA125 levels
biomarkers_tbl <- biomarkers_tbl %>% 
  left_join(first_date, by = "patient_id") %>%
  group_by(patient_id) %>%
  dplyr::arrange(laboratory_test_date) %>%
  dplyr::mutate(
    laboratory_test_date_diff = laboratory_test_date - first_date,
    laboratory_test_date = as.numeric(laboratory_test_date, units = "days"),
    laboratory_test_date_diff = as.numeric(laboratory_test_date_diff, units = "days")
    ) %>%
  dplyr::filter(laboratory_test_date_diff > 0 & !is.na(laboratory_test_date_diff)) %>%
  dplyr::mutate(
    laboratory_test_biomarker_level = as.numeric(laboratory_test_biomarker_level),
    laboratory_test_biomarker_level_baseline = laboratory_test_biomarker_level - first(laboratory_test_biomarker_level),
    laboratory_test_biomarker_level_diff = laboratory_test_biomarker_level - lag(laboratory_test_biomarker_level),
    laboratory_test_biomarker_level_minimum = rank(laboratory_test_biomarker_level, ties.method="first")==1,
    laboratory_test_biomarker_level_after_minimum = if_else(row_number() > which.min(laboratory_test_biomarker_level), "After min CA 125", "Before min CA 125")
    ) %>%
  ungroup %>%
  left_join(db$gyn_diagnosis %>%
              select(patient_id, gyn_diagnosis_chemo_intent_description), by = "patient_id")

# Recurrence events
recur <- recur %>% 
  left_join(first_date, by = "patient_id") %>%
  mutate(d = response_first_recurrence_ct_scan_date - response_pre_treatment_tissue_collection_date) %>% 
  select(patient_id, d) %>% 
  mutate(patient_id_short = str_remove(patient_id, "SPECTRUM-OV-")) %>% 
  filter(patient_id %in% biomarkers_tbl$patient_id)

# Death events
survival <- db$patients %>%
  left_join(first_date, by = "patient_id") %>%
  mutate(patient_overall_survival_date_diff = patient_overall_survival_date - first_date) %>%
  select(patient_id, patient_overall_survival_date_diff) %>%
  mutate(patient_id_short = str_remove(patient_id, "SPECTRUM-OV-")) %>%
  filter(patient_id %in% biomarkers_tbl$patient_id)

# cfDNA collection events
cfdna <- cfdna %>% 
  left_join(first_date, by = "patient_id") %>%
  filter(!is.na(specimen_lab_medicine_cfdna_total_yield)) %>% 
  group_by(patient_id) %>% 
  mutate(n_cfdna = n(), 
         min_cfdna = min(specimen_lab_medicine_cfdna_total_yield), 
         max_cfdna = max(specimen_lab_medicine_cfdna_total_yield), 
         mean_cfdna = mean(specimen_lab_medicine_cfdna_total_yield)) %>% 
  dplyr::mutate(
    specimen_lab_medicine_drawn_date_diff = 
      specimen_lab_medicine_drawn_date - first_date,
    specimen_lab_medicine_drawn_date = as.numeric(specimen_lab_medicine_drawn_date, units = "days"),
    specimen_lab_medicine_drawn_date_diff = as.numeric(specimen_lab_medicine_drawn_date_diff, units = "days")
    ) %>%
  ungroup() %>% 
  mutate(patient_id_short = str_remove(patient_id, "SPECTRUM-OV-")) %>% 
  select(patient_id, patient_id_short, specimen_lab_medicine_drawn_date, specimen_lab_medicine_cfdna_total_yield, n_cfdna, max_cfdna, min_cfdna, mean_cfdna, specimen_lab_medicine_drawn_date_diff) %>% 
  filter(patient_id_short %in% biomarkers_tbl$patient_id_short)

# Surgery events
surgery <- db$surgeries %>% 
  select(patient_id, patient_id_short, surgery_date) %>% 
  left_join(first_date) %>% 
  mutate(surgery_date_diff = surgery_date - first_date) %>% 
  mutate(surgery_date_diff = ifelse(surgery_date_diff < 0, 0, surgery_date_diff)) %>% #hack to remove negative dates
  filter(patient_id_short %in% biomarkers_tbl$patient_id_short)

```

#### All patients

```{r fig.height = 18, fig.width = 16}

p <- biomarkers_tbl %>%
  ggplot() +
  geom_line(aes(x=laboratory_test_date_diff, y=as.numeric(laboratory_test_biomarker_level)),color = "grey10") +
  geom_point(aes(x=laboratory_test_date_diff, y=as.numeric(laboratory_test_biomarker_level)), size=0.75) +
  geom_rect(data = recur,
            aes(xmin = d), xmax = Inf, ymin = 0, ymax = Inf, color = "grey60", alpha = .1) +
  geom_vline(data = cfdna,
             aes(xintercept = specimen_lab_medicine_drawn_date_diff, col = "cfDNA"),
             alpha = 0.75, lty = 2) +
  geom_vline(data = surgery, aes(xintercept = surgery_date_diff, col = "Surgery")) +
  geom_vline(data = survival, 
             aes(xintercept = patient_overall_survival_date_diff, col = "Deceased"),
             alpha = 0.75, lty = 2) +
  scale_x_continuous(breaks = scales::breaks_width(365)) +
  scale_y_log10(breaks = 10^(-1:10),
                labels = trans_format("log10", math_format(10^.x))) +
  labs(title=unique(biomarkers_tbl$laboratory_test_name), 
       x='Time from baseline (days)', y=unique(biomarkers_tbl$laboratory_test_biomarker_units), 
       color='') +
  theme(plot.title = element_text(size=14),
        panel.grid.major.x = element_line(size=.1, color="grey50", linetype = "dashed"),
        panel.grid.major.y = element_line(size=.1, color="grey50", linetype = "dashed")) +
  facet_wrap(patient_id_short ~ .) +
  # facet_wrap(glue::glue("{patient_id_short}\n{gyn_diagnosis_chemo_intent_description}") ~ .) +
  scale_color_manual(values = c("firebrick4", "deepskyblue4")) +
  panel_border()

p

ggsave_pdf(filename = "figures/220_cfdna_dynamics/220_cfdna_dynamics_all_patients.pdf", 
           p, width = 18, height = 16)
ggsave_png(filename = "figures/220_cfdna_dynamics/220_cfdna_dynamics_all_patients.png", 
           p, width = 18, height = 16)

```

#### scDNA patients

```{r fig.height = 12, fig.width = 12}

p <- biomarkers_tbl %>%
  filter(patient_id %in% scdna_patients) %>%
  ggplot() +
  geom_line(aes(x=laboratory_test_date_diff, y=as.numeric(laboratory_test_biomarker_level)),color = "grey10") +
  geom_point(aes(x=laboratory_test_date_diff, y=as.numeric(laboratory_test_biomarker_level)), size=0.75) +
  geom_rect(data = filter(recur, patient_id %in% scdna_patients),
            aes(xmin = d), xmax = Inf, ymin = 0, ymax = Inf, color = "grey60", alpha = .1) +
  geom_vline(data = filter(cfdna, patient_id %in% scdna_patients),
             aes(xintercept = specimen_lab_medicine_drawn_date_diff, col = "cfDNA"),
             alpha = 0.75, lty = 2) +
  # geom_vline(data = surgery, aes(xintercept = surgery_date2, col = "Surgery")) +
  geom_vline(data = filter(survival, patient_id %in% scdna_patients), 
             aes(xintercept = patient_overall_survival_date_diff, col = "Deceased"),
             alpha = 0.75, lty = 2) +
  scale_x_continuous(breaks = scales::breaks_width(365)) +
  scale_y_log10(breaks = 10^(-1:10),
                labels = trans_format("log10", math_format(10^.x))) +
  labs(title=unique(biomarkers_tbl$laboratory_test_name), 
       x='Time from baseline (days)', y=unique(biomarkers_tbl$laboratory_test_biomarker_units), 
       color='') +
  theme(plot.title = element_text(size=14),
        panel.grid.major.x = element_line(size=.1, color="grey50", linetype = "dashed"),
        panel.grid.major.y = element_line(size=.1, color="grey50", linetype = "dashed")) +
  facet_wrap(patient_id_short ~ .) +
  scale_color_manual(values = c("firebrick4", "deepskyblue4")) +
  panel_border()

p

ggsave_pdf(filename = "figures/220_cfdna_dynamics/220_cfdna_dynamics_scdna_patients.pdf", 
           p, width = 12, height = 12)
ggsave_png(filename = "figures/220_cfdna_dynamics/220_cfdna_dynamics_scdna_patients.png", 
           p, width = 12, height = 12)

```